name: Java CI/CD
on: 
  # push: 
  #   branches: master
  #   paths-ignore:
  #     - './.github/workflows/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  run-reusable-workflow:
    name: "Java CI/CD"
    uses: dhruv-development/reusable_workflows/.github/workflows/java-ci-cd.yml@main
    with:
      role-assume: "arn:aws:iam::410454990341:role/GitHubActionsRole"
      AWS_REGION: "us-east-2"
      ECR_REPO: "java-new"
      TASK_DEFINITION: "java-app-task-definition"
      CONTAINER_NAME: "java-container"
      CLUSTER: "java-cluster"
      SERVICE: "java-service"
