name: Java CI/CD
on: 
  push: 
    branches: master
    # paths-ignore:
    #   - ./github/workflows/*

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-reusable-workflow:
    name: "Java CI/CD"
    uses: dhruv-development/java-quotes-app/.github/workflows/java-ci-cd.yml@master
    with:
      role-assume: "arn:aws:iam::410454990341:role/GitHubActionsRole"
      AWS_REGION: "us-east-2"
      ECR_REPO: "java-new"
      TASK_DEFINITION: "new-java-task-definition"
      CONTAINER_NAME: "new-java"
      CLUSTER: "java-new"
      SERVICE: "new-java-service"
